WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

VIRTUAL_WIDTH = 288
VIRTUAL_HEIGHT = 208

GROUND_LEVEL = 9

TILE_SIZE = 16
TILE_TOP_ID = 22
TILE_INNER_ID = 39
TILE_EMPTY_ID = 1

GRAVITY = 6

PLAYER_WIDTH = 50
PLAYER_HEIGHT = 37

PLAYER_WALK_SPEED = 100
PLAYER_JUMP_VELOCITY = -200

PLAYER_HURTBOX_OFFSET_X = 20
PLAYER_HURTBOX_OFFSET_Y = 0
PLAYER_HURTBOX_OFFSET_WIDTH = -40
PLAYER_HURTBOX_OFFSET_HEIGHT = 0

PLAYER_HITBOX_OFFSET_X_LEFT = 5
PLAYER_HITBOX_OFFSET_X_RIGHT = 30
PLAYER_HITBOX_OFFSET_Y = 0
PLAYER_HITBOX_OFFSET_WIDTH = -35
PLAYER_HITBOX_OFFSET_HEIGHT = 0

LEFT = 'a'
RIGHT = 'd'
JUMP = 'space'